# Generated by Django 5.0 on 2026-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cpf_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Contato'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site / WhatsApp'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
