# Generated by Django 5.0 on 2025-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venda_desconto_venda_desconto_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Valor em caixa no início', max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, help_text='Valor em caixa no fechamento', max_digits=10)),
                ('operador', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('notas_100', models.IntegerField(default=0)),
                ('notas_50', models.IntegerField(default=0)),
                ('notas_20', models.IntegerField(default=0)),
                ('notas_10', models.IntegerField(default=0)),
                ('notas_5', models.IntegerField(default=0)),
                ('notas_2', models.IntegerField(default=0)),
                ('moedas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
