# Generated by Django 5.0 on 2026-03-20 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historico_status_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='imei2',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='IMEI 2 deve ter 15 dígitos', regex='^\\d{15}$')]),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='imei2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI 2 deve ter até 15 dígitos', regex='^\\d{0,15}$')]),
        ),
        migrations.AddField(
            model_name='serialproduto',
            name='imei2',
            field=models.CharField(blank=True, help_text='IMEI 2 (somente para celulares dual SIM)', max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI 2 deve ter até 15 dígitos', regex='^\\d{0,15}$')]),
        ),
        migrations.AlterField(
            model_name='serialproduto',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI 1 (somente para celulares)', max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI deve ter até 15 dígitos', regex='^\\d{0,15}$')]),
        ),
    ]
