# Generated by Django 5.0 on 2026-04-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_imei2_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitente',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome fantasia (opcional). Se preenchido, será exibido nos relatórios.', max_length=200),
        ),
    ]
