# Generated by Django 5.0 on 2026-04-02 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_emitente_nome_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI 1 (somente para celulares)', max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI deve ter até 15 dígitos', regex='^\\d{0,15}$')]),
        ),
        migrations.AddField(
            model_name='produto',
            name='imei2',
            field=models.CharField(blank=True, help_text='IMEI 2 (somente para celulares dual SIM)', max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI 2 deve ter até 15 dígitos', regex='^\\d{0,15}$')]),
        ),
    ]
