# Generated by Django 5.0 on 2026-04-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_produto_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='serial_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='core.serialproduto', verbose_name='Serial/IMEI da unidade'),
        ),
    ]
