# Generated by Django 5.0 on 2025-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço de compra', max_digits=10),
        ),
    ]
