# Generated by Django 5.0 on 2026-03-07 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fornecedor_campos_extras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatusOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(max_length=30)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='core.ordemservico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Status OS',
                'verbose_name_plural': 'Histórico de Status OS',
                'ordering': ['data_hora'],
            },
        ),
    ]
