# Generated by Django 5.0 on 2025-10-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_preco_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto em reais', max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto em porcentagem', max_digits=5),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'PIX'), ('parcelado', 'Parcelado')], default='dinheiro', max_length=50),
        ),
    ]
