# Generated by Django 5.0 on 2026-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fornecedor_campos_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
