# Generated by Django 5.0 on 2025-10-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('boleto', 'Boleto')], default='dinheiro', max_length=50),
        ),
    ]
