# Generated by Django 5.0 on 2026-02-28 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_licenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_previsao', models.DateField(blank=True, help_text='Previsão de entrega', null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('aparelho', models.CharField(help_text='Ex: Samsung Galaxy A54', max_length=200)),
                ('imei', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI deve ter até 15 dígitos', regex='^\\d{0,15}$')])),
                ('acessorios', models.CharField(blank=True, help_text='Capinha, carregador, etc.', max_length=300)),
                ('tipo_servico', models.CharField(choices=[('troca_tela', 'Troca de Tela'), ('troca_bateria', 'Troca de Bateria'), ('reparo_placa', 'Reparo de Placa'), ('conector_carga', 'Conector de Carga'), ('desbloqueio', 'Desbloqueio'), ('software', 'Problema de Software'), ('troca_camera', 'Troca de Câmera'), ('reparo_botoes', 'Reparo de Botões'), ('limpeza', 'Limpeza / Higienização'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('descricao_problema', models.TextField(help_text='Descrição do defeito relatado pelo cliente')),
                ('observacoes_tecnico', models.TextField(blank=True, help_text='Notas internas do técnico')),
                ('valor_orcamento', models.DecimalField(decimal_places=2, default=0, help_text='Valor do orçamento', max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado no fechamento', max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'PIX'), ('parcelado', 'Parcelado')], default='', max_length=50)),
                ('garantia_dias', models.IntegerField(default=90, help_text='Prazo de garantia do serviço em dias')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('orcamento_enviado', 'Orçamento Enviado'), ('aprovado', 'Aprovado'), ('concluido', 'Concluído'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando', max_length=30)),
                ('tecnico', models.CharField(blank=True, help_text='Nome do técnico responsável', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
