# Generated by Django 5.0 on 2026-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5, help_text='Alerta quando estoque atingir este valor'),
        ),
    ]
