# Generated by Django 5.0 on 2026-03-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_foto_barcode_serial_emitente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='parcelas',
            field=models.IntegerField(default=1, help_text='Número de parcelas (para crédito/parcelado)'),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('motivo', models.CharField(choices=[('defeito', 'Defeito / Falha'), ('arrependimento', 'Arrependimento'), ('produto_errado', 'Produto Errado'), ('danificado_entrega', 'Danificado na Entrega'), ('outro', 'Outro')], default='defeito', max_length=30)),
                ('tipo', models.CharField(choices=[('devolucao', 'Devolução (reembolso)'), ('troca', 'Troca por outro produto'), ('credito', 'Crédito em loja')], default='devolucao', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do problema')),
                ('valor_reembolso', models.DecimalField(decimal_places=2, default=0, help_text='Valor devolvido ao cliente', max_digits=10)),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.CharField(default='Sistema', max_length=200)),
                ('repor_estoque', models.BooleanField(default=True, help_text='Devolver o produto ao estoque?')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.produto')),
                ('venda', models.ForeignKey(help_text='Venda de origem', on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.venda')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-data_devolucao'],
            },
        ),
    ]
