# Generated by Django 5.0 on 2026-02-28 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitente',
            name='ativo',
            field=models.BooleanField(default=False, help_text='Emitente padrão para documentos'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='EAN-13 ou outro código de barras', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do produto', null=True, upload_to='produtos/'),
        ),
        migrations.CreateModel(
            name='SerialProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Número de série', max_length=100, unique=True)),
                ('imei', models.CharField(blank=True, help_text='IMEI (somente para celulares)', max_length=15, validators=[django.core.validators.RegexValidator(message='IMEI deve ter até 15 dígitos', regex='^\\d{0,15}$')])),
                ('status', models.CharField(choices=[('em_estoque', 'Em Estoque'), ('vendido', 'Vendido'), ('em_reparo', 'Em Reparo / OS'), ('devolvido', 'Devolvido')], default='em_estoque', max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=300)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriais', to='core.produto')),
            ],
            options={
                'verbose_name': 'Serial / IMEI',
                'verbose_name_plural': 'Seriais / IMEIs',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
