# Generated by Django 5.0 on 2025-10-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compra_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('data_ativacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'ordering': ['-data_ativacao'],
            },
        ),
    ]
